// Code generated by "dataclass -type Query -field Key string|Value string -output query_dataclass_generated.go"; DO NOT EDIT.

package query

type Query interface {
	Key() string
	Value() string
}
type query struct {
	key   string
	value string
}

func (s *query) Key() string   { return s.key }
func (s *query) Value() string { return s.value }
func NewQuery(
	key string,
	value string,
) Query {
	return &query{
		key:   key,
		value: value,
	}
}
